In [3]:
import os
os.environ['AOC_SESSION'] = '53616c7465645f5f37c74a4bd1a2394b4fa5dcbb449244bb183873f839c409c1c2b5d3191175e6de6040979aeb78f7894665a168392bc55c2d58d905f027b397'

In [4]:
import aocd
from aocd.models import Puzzle
day = 13
year = 2024
puzzle = Puzzle(year=year, day=day)
# data = aocd.get_data(day=day, year=year)
with open('./data/input_{:02d}'.format(day), 'w') as fh:
    fh.write(puzzle.input_data)

In [19]:
test_data = """Button A: X+94, Y+34
Button B: X+22, Y+67
Prize: X=8400, Y=5400

Button A: X+26, Y+66
Button B: X+67, Y+21
Prize: X=12748, Y=12176

Button A: X+17, Y+86
Button B: X+84, Y+37
Prize: X=7870, Y=6450

Button A: X+69, Y+23
Button B: X+27, Y+71
Prize: X=18641, Y=10279"""
data_test = test_data.splitlines()

In [20]:
data = puzzle.input_data.splitlines()
len(data), data[:10]

(1279,
 ['Button A: X+23, Y+57',
  'Button B: X+58, Y+28',
  'Prize: X=11852, Y=17598',
  '',
  'Button A: X+41, Y+97',
  'Button B: X+88, Y+65',
  'Prize: X=8250, Y=10497',
  '',
  'Button A: X+15, Y+81',
  'Button B: X+78, Y+15'])

In [101]:
def getXY(string):
    x, y = list(map(lambda x: int(x[2:]), string[10:].split(', ')))
    return x, y    

def parse(line):
    A, B, P = line.split('\n')
    ax, ay = getXY(A)
    bx, by = getXY(B)
    X, Y = list(map(lambda x: int(x[2:]), P[7:].split(", ")))
    return dict(ax=ax, ay=ay, bx=bx, by=by, X=X, Y=Y)

def isint(x):
    return int(x) == x

def solveA(m, B):
    i = m['X'] - B*m['bx']
    if not isint(i):
        return -1
    A = i / m['ax']
    if not isint(A) or A < 0 or A > 100:
        return -1
    return int(A)

def solve_machine(m):
    min_cost = None
    min_AB = None
    for B in range(100):
        A = solveA(m, B)
        if not (A*m['ay'] + B* m['by'] == m['Y']):
            continue
        if A > -1:
            cost = 3*A + B
            if min_cost is None or cost < min_cost:
                min_cost = cost
                min_AB = (A, B)
    # if min_cost is None:
    #     return 0
    # return min_cost
    return min_cost if min_cost else 0, min_AB
        

In [144]:
d = puzzle.input_data
# d = test_data
data = d.split("\n\n")

machines = [parse(m) for m in data]
# machines

In [103]:
res = sum([solve_machine(m)[0] for m in machines])
res

28753

In [104]:
puzzle.answer_a = res

That's the right answer!  You are one gold star closer to finding the Chief Historian. [Continue to Part Two]


In [105]:
# Part 2

In [185]:
def solve_machine_2(m):
    B = (m['Y']*m['ax'] - m['X']*m['ay']) / (m['by']*m['ax'] - m['bx']*m['ay'])
    A = (m['Y']*m['bx'] - m['X']*m['by']) / (m['bx']*m['ay'] - m['by']*m['ax'])
    if not isint(B) or not isint(A):
        return 0
    return int(3*A+B)
    return (A, B)
    A = solveA(m, B)
    return (A, B)
    if not isint(A) or A == -1:
        return 0
    
    

In [188]:
d = puzzle.input_data
# d = test_data
data = d.split("\n\n")

machines = [parse(m) for m in data]

offset = 10000000000000
# offset = 0
for m in machines:
    m['X'] += offset
    m['Y'] += offset
# machines

In [189]:
res = sum([solve_machine_2(m) for m in machines])
res

102718967795500

In [190]:
puzzle.answer_b = res

That's the right answer!  You are one gold star closer to finding the Chief Historian.You have completed Day 13! You can [Shareon
  Bluesky
Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


In [191]:
import re, numpy as np

def solve(d):
    a,b,c,d,x,y = map(int,re.findall(r'\d+',d))

    M = np.array([[a,c], [b,d]])
    P = np.array([x,y]) + p
    R = np.linalg.solve(M, P).round()
    return R @ [3, 1] if all(M @ R == P) else 0

D = open('./data/input_13').read().split('\n\n')
for p in 0,1e13: print(int(sum(map(solve, D))))

28753
102718967795500


In [204]:
# d = puzzle.input_data
d = test_data
data = d.split("\n\n")

machines = [parse(m) for m in data]

In [205]:
machines[1]

{'ax': 26, 'ay': 66, 'bx': 67, 'by': 21, 'X': 12748, 'Y': 12176}

In [218]:
m = machines[0]
M = np.array([[m['ax'],m['bx']], [m['ay'],m['by']]])
P = np.array([m['X'],m['Y']]) + 0
R = np.linalg.solve(M, P)#.round()

In [219]:
m

{'ax': 94, 'ay': 34, 'bx': 22, 'by': 67, 'X': 8400, 'Y': 5400}

In [220]:
R

array([80., 40.])

In [212]:
M @ R

array([12711., 12141.])

In [213]:
P

array([12748, 12176])

In [203]:
P

array([10000000011852, 10000000017598])