In [79]:
import pandas as pd
import numpy as np

In [20]:
with open('data/input_07.txt') as fh:
    file_input = fh.read().strip()

In [98]:
test_input = """Step C must be finished before step A can begin.
Step C must be finished before step F can begin.
Step A must be finished before step B can begin.
Step A must be finished before step D can begin.
Step B must be finished before step E can begin.
Step D must be finished before step E can begin.
Step F must be finished before step E can begin."""

In [119]:
# inp = test_input.split('\n')
inp = file_input.split('\n')

Part A

In [120]:
df = pd.DataFrame(list(map(lambda x: (x[5], x[36]), inp)))
steps = set(df[0].values.tolist() + df[1].values.tolist())
step_order = []
left = steps.copy()

while left:
    next_step = min(left - set(df[1].values))
    step_order.append( next_step)
    left -= set([next_step])
    df = df[df[0] != next_step]

print ("".join(step_order))


ABLCFNSXZPRHVEGUYKDIMQTWJO


Part B

In [122]:
ctime = lambda x: ord(x) - ord('A') + 1 + 60
idle = lambda x: np.sum(workers[:, 0] == 0)
next_idle_worker = lambda: np.where(workers[:, 0] == 0)[0][0]

n_workers = 5
workers = np.zeros((n_workers, 2))

df = pd.DataFrame(list(map(lambda x: (x[5], x[36]), inp)))
steps = set(df[0].values.tolist() + df[1].values.tolist())
step_order = []
left = steps.copy()
available = set([])
running = set([])

seconds = 0
while left or available or np.sum(workers):
    print("second: ", seconds)
    workers[workers[:, 0]>0, 1] -= 1    
    finished = (workers[:, 0] != 0) & (workers[:, 1] ==0)
    print ("finished: ", finished)
    if finished.any():
        for step in workers[finished, 0]:
            rm = chr(int(step))
            left -= set([rm])
            df = df[df[0] != rm]
            print("removed", rm)
        workers[finished, 0] = 0.
    available = (left - set(df[1].values) - running)    
    while available and idle(workers):
        i = next_idle_worker()
        print('idle', i)
        step = available.pop()
        running.add(step)
        print('step', step)
        workers[i, 0] = ord(step)
        workers[i, 1] = ctime(step)
    #left -= set([next_step])
    #df = df[df[0] != next_step]
    
    seconds += 1
    print (workers)
    print ("#############")        

print (workers)
print ("Seconds: %d" % (seconds - 1))

second:  0
finished:  [False False False False False]
idle 0
step B
idle 1
step A
idle 2
step Z
idle 3
step X
[[66. 62.]
 [65. 61.]
 [90. 86.]
 [88. 84.]
 [ 0.  0.]]
#############
second:  1
finished:  [False False False False False]
[[66. 61.]
 [65. 60.]
 [90. 85.]
 [88. 83.]
 [ 0.  0.]]
#############
second:  2
finished:  [False False False False False]
[[66. 60.]
 [65. 59.]
 [90. 84.]
 [88. 82.]
 [ 0.  0.]]
#############
second:  3
finished:  [False False False False False]
[[66. 59.]
 [65. 58.]
 [90. 83.]
 [88. 81.]
 [ 0.  0.]]
#############
second:  4
finished:  [False False False False False]
[[66. 58.]
 [65. 57.]
 [90. 82.]
 [88. 80.]
 [ 0.  0.]]
#############
second:  5
finished:  [False False False False False]
[[66. 57.]
 [65. 56.]
 [90. 81.]
 [88. 79.]
 [ 0.  0.]]
#############
second:  6
finished:  [False False False False False]
[[66. 56.]
 [65. 55.]
 [90. 80.]
 [88. 78.]
 [ 0.  0.]]
#############
second:  7
finished:  [False False False False False]
[[66. 55.]
 [65. 54.]
