In [1]:
with open('./data/input_12.txt') as fh:
    file_input = fh.read().strip()

In [54]:
test = """<x=-1, y=0, z=2>
<x=2, y=-10, z=-7>
<x=4, y=-8, z=8>
<x=3, y=5, z=-1>"""

In [2]:
test2 = """<x=-8, y=-10, z=0>
<x=5, y=5, z=10>
<x=2, y=-7, z=3>
<x=9, y=-8, z=-3>"""

In [35]:
import numpy as np
from itertools import combinations

In [158]:
import re
def parse(txt):
    return np.array([list(map(int, re.findall('[-0-9]+', line))) for line in txt.split('\n')])



def simulate(pos, vel, steps=1):
    n = pos.shape[0]
    init_pos = pos.copy()
    init_vel = vel.copy()
    for step in range(steps):
        for i, j in combinations(range(n), 2):
            dv = np.sign(pos[j] - pos[i])
            vel[i] += dv
            vel[j] -= dv
        pos += vel
    return pos, vel

def energy(pos, vel):
    return np.sum(np.abs(pos).sum(axis=1) * np.abs(vel).sum(axis=1))

In [159]:
# test
pos = parse(test)
vel = np.zeros(pos.shape, dtype=pos.dtype)
# print(pos, vel)
pos, vel = simulate(pos, vel, 10)
print(pos)
print(vel)
print(energy(pos, vel))

[[ 2  1 -3]
 [ 1 -8  0]
 [ 3 -6  1]
 [ 2  0  4]]
[[-3 -2  1]
 [-1  1  3]
 [ 3  2 -3]
 [ 1 -1 -1]]
179


In [160]:
# After 10 steps:
# pos=<x= 2, y= 1, z=-3>, vel=<x=-3, y=-2, z= 1>
# pos=<x= 1, y=-8, z= 0>, vel=<x=-1, y= 1, z= 3>
# pos=<x= 3, y=-6, z= 1>, vel=<x= 3, y= 2, z=-3>
# pos=<x= 2, y= 0, z= 4>, vel=<x= 1, y=-1, z=-1>

In [161]:
# part 1
pos = parse(file_input)
vel = np.zeros(pos.shape, dtype=pos.dtype)
# print(pos, vel)
pos, vel = simulate(pos, vel, 1000)
print(pos)
print(vel)
print(energy(pos, vel))

[[ 87   0 -16]
 [-39  18  62]
 [  1 -21 -20]
 [-36 -30 -56]]
[[  0   9   8]
 [  7  -4   4]
 [  9   4 -12]
 [-16  -9   0]]
7636


In [181]:
# part 2
def simulate_period(pos, vel):
    n = pos.shape[0]
    init_pos = pos.copy()
    init_vel = vel.copy()
    steps = 0
    while True:
        for i, j in combinations(range(n), 2):
            dv = np.sign(pos[j] - pos[i])
            vel[i] += dv
            vel[j] -= dv
        pos += vel
        steps += 1
        if (pos == init_pos).all() and (vel == 0).all():
            break
    return steps, pos, vel

In [182]:
test

'<x=-1, y=0, z=2>\n<x=2, y=-10, z=-7>\n<x=4, y=-8, z=8>\n<x=3, y=5, z=-1>'

In [183]:
# test
pos = parse(test)
vel = np.zeros(pos.shape, dtype=pos.dtype)
for i in range(3):
    p, v = simulate(pos[:, i], vel[:, i], steps=2772)
    print (i, p, v)

0 [-1  2  4  3] [0 0 0 0]
1 [  0 -10  -8   5] [0 0 0 0]
2 [ 2 -7  8 -1] [0 0 0 0]


In [185]:
pos = parse(test)
vel = np.zeros(pos.shape, dtype=pos.dtype)
for i in range(3):
    s, p, v = simulate_period(pos[:, i], vel[:, i])
    print (i, s, p, v)

0 18 [-1  2  4  3] [0 0 0 0]
1 28 [  0 -10  -8   5] [0 0 0 0]
2 44 [ 2 -7  8 -1] [0 0 0 0]


In [189]:
np.lcm(np.lcm(18, 28), 44)

2772

In [192]:
# part 2
# calculate dimensions independently and find period
pos = parse(file_input)
vel = np.zeros(pos.shape, dtype=pos.dtype)
period = []
for i in range(3):
    s, p, v = simulate_period(pos[:, i], vel[:, i])
    period.append(s)
    print (i, s, p, v)

0 161428 [12 -8  7  2] [0 0 0 0]
1 193052 [  0  -5 -17 -11] [0 0 0 0]
2 144624 [-15 -10   1  -6] [0 0 0 0]


In [193]:
# calculate lowest common multiple of periods
np.lcm(np.lcm(period[0], period[1]), period[2])


281691380235984