In [1]:
# To continue, please consult the code grid in the manual.  Enter the code at row 2981, column 3075.
code_row = 2981
code_col = 3075

In [2]:
import numpy as np

In [3]:
def ncode(c, r):
    ir = (r * (r - 1)) / 2 + 1
    return ir + (c**2 + 2*r*c - 2*r - c) / 2

def next_code(code):
    return (code * 252533) % 33554393
    
    

In [4]:
num_code = ncode(code_col, code_row)
print num_code

18331560


In [16]:
code = 20151125
n = num_code
for i in range(n-1):
    code = next_code(code)
    if not i % 1000000:
        print i, code
print i, code, next_code(code)

0 31916031
1000000 29842942
2000000 25306945
3000000 25890237
4000000 15345957
5000000 14607377
6000000 24891547
7000000 28853079
8000000 24480810
9000000 3853235
10000000 29439364
11000000 15295491
12000000 10864205
13000000 25425550
14000000 23788531
15000000 3489257
16000000 13943617
17000000 5850411
18000000 23633312
18331558 9132360 28836990


In [6]:
a = np.zeros((7, 7))
for r in range(1, 7):
    for c in range(1, 7):
        a[r, c] = ncode(c , r)
print a

[[  0.   0.   0.   0.   0.   0.   0.]
 [  0.   1.   3.   6.  10.  15.  21.]
 [  0.   2.   5.   9.  14.  20.  27.]
 [  0.   4.   8.  13.  19.  26.  34.]
 [  0.   7.  12.  18.  25.  33.  42.]
 [  0.  11.  17.  24.  32.  41.  51.]
 [  0.  16.  23.  31.  40.  50.  61.]]


In [10]:
20151125 * (252533 ** 60) % 33554393

27995004L

In [26]:
7 * 6 - 12

30