In [18]:
import numpy as np
from random import randint

In [12]:
ingredient = {}
properties = []
ni = 0
with open('day15.txt', 'r') as f:
    for line in f:
        w = line.split()
        ingredient[ni] = w[0][:-1]
        properties.append( map(int, [w[2][:-1], w[4][:-1], w[6][:-1], w[8][:-1], w[10]]) )
        ni += 1

In [15]:
ingredient, properties

({0: 'Sugar', 1: 'Sprinkles', 2: 'Candy', 3: 'Chocolate'},
 [[3, 0, 0, -3, 2], [-3, 3, 0, 0, 9], [-1, 0, 4, 0, 1], [0, 0, -2, 2, 8]])

In [16]:
print line, ingredient

Chocolate: capacity 0, durability 0, flavor -2, texture 2, calories 8
{0: 'Sugar', 1: 'Sprinkles', 2: 'Candy', 3: 'Chocolate'}


In [106]:
def score(x, p, ts = 100):
    add = np.sum(p.T * x, axis = 1)
    return reduce(lambda a, b: max(a, 0) * max(b, 0), add)

In [107]:
p = np.array(properties)

In [108]:
p[:, :-1]

array([[ 3,  0,  0, -3],
       [-3,  3,  0,  0],
       [-1,  0,  4,  0],
       [ 0,  0, -2,  2]])

In [109]:
x = np.array([20, 0, 30, 30])

In [110]:
p.T * x

array([[ 60,   0, -30,   0],
       [  0,   0,   0,   0],
       [  0,   0, 120, -60],
       [-60,   0,   0,  60],
       [ 40,   0,  30, 240]])

In [111]:
np.sum(p.T * x, axis = 1)

array([ 30,   0,  60,   0, 310])

In [112]:
score(np.array([54, 45,  3, -2]), p[:, :-1])


0

In [93]:
maxscore = 0
i = 0
nprop = 4
for i in range(1000000):
    left = 100
    x = np.zeros(nprop)
    for j in range(nprop-1):
        x[j] = randint(left)
        left -= x[j]
    x[nprop - 1] = left
    s = score(x, p[:, :-1])
    if s > maxscore:
        maxscore = s
        print i, s, x, sum(x)
    
    

204 37044.0 [ 27.   2.  26.  45.] 100.0
2450 52272.0 [ 24.  12.  25.  39.] 100.0
2965 155520.0 [ 24.   4.  30.  42.] 100.0
4813 188370.0 [ 23.   5.  31.  41.] 100.0
10872 198000.0 [ 21.   3.  32.  44.] 100.0
22541 213750.0 [ 21.   5.  33.  41.] 100.0
64135 220248.0 [ 21.   4.  32.  43.] 100.0
282206 222870.0 [ 21.   5.  31.  43.] 100.0


In [131]:
# 117936
maxscore = 0
i = 0
nprop = 4
for i in range(1000000):
    left = 100
    x[1] = randint(50)
    left -= x[1]
    x[3] = randint( max( ((300 - 7 * x[1]) // 6) + 1, 0), (400 - 8 * x[1]) // 7)
    x[0] = 400 - (8*x[1] + 7* x[3])
    x[2] = 100 - x[0] - x[1] - x[3]
    s = score(x, p[:, :-1])
    if s > maxscore:
        maxscore = s
        print i, s, x, sum(x)

40 92736 [18  4 28 50] 100
830 117936 [21  8 26 45] 100


In [149]:
x = np.array([24, 12, 25, 39])
pp = p[:, :-1]
nprop = 4
for i in range(40):
    s = score(x, pp)
    if i % 2:
        ch = -1
    else:
        ch = +1
    cand = []
    for j in range(nprop):
        y = x.copy()
        y[j] += ch
        cand.append(score(y, pp))
    ind = cand.index(max(cand))
    print ch, ind, cand
    x[ind] += ch
x, score(x, p[:, :-1])

1 3 [33264, 41184, 56160, 63360]
-1 1 [63360, 73920, 55296, 52272]
1 3 [56100, 63360, 82368, 83160]
-1 1 [84942, 91800, 69300, 73920]
1 2 [75600, 83160, 105600, 97920]
-1 1 [111540, 112860, 91800, 92160]
1 2 [91476, 105600, 126360, 123120]
-1 0 [136890, 131040, 112860, 108864]
1 2 [126360, 121680, 147420, 145800]
-1 1 [142560, 159120, 136890, 133056]
1 3 [144000, 147420, 169728, 171360]
-1 1 [169344, 176400, 155520, 159120]
1 2 [162288, 171360, 191520, 185640]
-1 0 [193536, 190080, 176400, 176358]
1 2 [191520, 179712, 204120, 201600]
-1 1 [190512, 209952, 193536, 191520]
1 2 [204120, 204120, 220320, 220320]
-1 1 [211680, 216000, 209952, 205632]
1 3 [207000, 220320, 225720, 228000]
-1 0 [222870, 209760, 214200, 216000]
1 2 [228000, 220248, 231840, 229500]
-1 2 [212940, 220248, 222870, 221760]
1 2 [228000, 220248, 231840, 229500]
-1 2 [212940, 220248, 222870, 221760]
1 2 [228000, 220248, 231840, 229500]
-1 2 [212940, 220248, 222870, 221760]
1 2 [228000, 220248, 231840, 229500]
-1 2 [2129

(array([21,  5, 31, 43]), 222870)

In [143]:
list(permutations(range(5), 2))

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (1, 0),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 0),
 (2, 1),
 (2, 3),
 (2, 4),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 4),
 (4, 0),
 (4, 1),
 (4, 2),
 (4, 3)]