In [1]:
#%pylab inline

In [2]:
import numpy as np
import matplotlib.animation as animation

In [22]:
n = 100
#n = 6
grid = np.zeros((n, n), dtype = np.int8)
ngb  = np.zeros((n, n))
row = 0
#with open('day18.txt_test', 'r') as f:
with open('day18.txt', 'r') as f:
    for line in f:
        col = 0
        for c in line:
            if c == '#':
                grid[row, col] = 1
            col += 1
        row += 1
                
def add2ngb(x, y):
    for i in range(max(0,x-1), min(n, x+2)):
        for j in range(max(0,y-1), min(n, y+2)):
            if i==x and j==y:
                continue
            ngb[i, j] += 1
        
def advance():
    ngb[:] = 0
    for i in range(n):
        for j in range(n):
            if grid[i, j]: 
                add2ngb(i, j)
                
    for i in range(n):
        for j in range(n):
            if grid[i, j]:
                if ngb[i, j] < 2 or ngb[i, j] > 3:
                    grid[i, j] = 0
            else:
                if ngb[i, j] == 3:
                    grid[i, j] = 1
save_ic = grid.copy()

In [ ]:
grid = save_ic.copy()
f = plt.figure(figsize=(8, 8))

def show_grid(x, y):
    return ~grid[x, y]


im = plt.imshow(~grid, cmap='hot', animated=True, interpolation='none')
i = 0

def updatefig(*args):
    global grid, i
    advance()
    im.set_array(~grid)    
    i += 1
    plt.title("step = %3d" % i)
    return im,

ani = animation.FuncAnimation(f, updatefig, interval=0, blit=True, frames=100)
ani.save('conway.gif', writer='imagemagick', fps=8);
#plt.show()
    

In [93]:
grid[[0, 0, n-1, n-1] , [0, n-1, 0, n-1]]

array([0, 1, 1, 0], dtype=int8)

In [68]:
for i in range(100):
    if not i % 10:
        print i
    advance()

0
10
20
30
40
50
60
70
80
90


In [69]:
print sum(grid)

814


In [51]:
grid, ngb

(array([[0, 0, 1, 1, 0, 0],
        [0, 0, 1, 1, 0, 1],
        [0, 0, 0, 1, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [1, 0, 1, 1, 0, 0]], dtype=int8),
 array([[ 1.,  0.,  3.,  2.,  4.,  1.],
        [ 2.,  2.,  3.,  2.,  4.,  3.],
        [ 0.,  2.,  2.,  3.,  3.,  1.],
        [ 2.,  4.,  1.,  2.,  2.,  2.],
        [ 2.,  6.,  4.,  4.,  2.,  0.],
        [ 2.,  4.,  3.,  2.,  2.,  1.]]))

In [55]:
advance()
print grid, ngb

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]] [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  2.  1.  0.]
 [ 0.  2.  3.  3.  2.  0.]
 [ 0.  2.  3.  3.  2.  0.]
 [ 0.  1.  2.  2.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [56]:
imshow(grid)